name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
     sdk: flutter
  google_maps_flutter: ^2.0.6
  english_words: ^4.0.0
  provider: ^6.0.0
  animated_background: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^0.67.0
  flutter_splash_screen: ^3.0.0
  video_player: ^2.1.13
  flutter_blue: ^0.8.0
  charts_flutter: ^0.12.0
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^3.0.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/wheelchair_autocad1.jpg
    - assets/images/maps.png
    - assets/images/naina2.jpg
    - assets/images/logo.png
    - assets/images/background_image.avif
    - assets/videos/bleh.mp4
    - assets/images/background2.avif
    - assets/wheelchair_moveease.obj
    - assets/images/moveease_mp4.mp4